[package]
name = "SuiNSSocialLayer"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
suins = { git = "https://github.com/MystenLabs/suins-contracts", rev = "releases/core/4", subdir = "packages/suins", override = true }

[addresses]
suins_social_layer = "0x0"
